name: Build and Push Frontend to GHCR

on:
  pull_request:
  push:
    branches:
      - dev
    paths:
      - "frontend/**"
      - ".github/workflows/frontend**"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: false
          tags: ghcr.io/stephen-hallett/frontend:latest
          platforms: linux/amd64

      - name: Build and push Docker image
        if: github.event_name == 'push' && success()
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/stephen-hallett/frontend:latest
          platforms: linux/amd64

  deploy:
    needs: build
    if: github.event_name == 'push' && success()
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Login via Azure cli"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ghcr.io/stephen-hallett/frontend:latest
